### PR TITLE
Document alternative way of allocate node

### PR DESCRIPTION
**Pull request by dmitry**
Normally this will be enough, for example for browserify.

### CODE REVIEW

**Comment by koenpunt** [comment]
Thanks, but this change defies the use of this gem. What problem are you trying to solve?

**Comment by dmitry** [comment]
@koenpunt I'm using `rails-browserify` and it calls `node` from the `browserify` while asset compilation, so mapping of `node` command doesn't work there, as it calls not with the capistrano `execute` method. So the only way of making `browserify` work is to push `PATH` of node bins path to the environment, so the shell could find it.

**Comment by dmitry** [comment]
@koenpunt it could be helpful for anyone, who forgot there are an alternative way to inject node/npm commands into the shell.

**Comment by koenpunt** [comment]
You can set that in the browserify_rails config:

    config.browserify_rails.node_bin = "/home/user/.nvm/versions/node/v7.0.0/bin/"

And if you don't want to hardcode the path in your source, use a custom environment variable, e.g. `BROWSERIFY_NODE_BIN`

**Comment by koenpunt** [comment]
I think that if you add `rake` to `nvm_map_bins`, it should work too.

**Comment by dmitry** [comment]
`config.browserify_rails.node_bin` will try to get `browserify` cli at `/home/user/.nvm/versions/node/v7.0.0/bin/` in such case. I tried, it didn't work. Tried to pass `NODE_PATH`, with exercis mode - didn't work too. With `rake` I guess it should work, haven't thought that `assets:precompile` is just a rake task that runs browserify from sprockets. Sometimes it's good to notice such cases somewhere in the README. 

My suggestion is to write few lines into the readme, to reduce such kind of issues.

**Pull request closed without merging**
